import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '@/components/Header';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossOrigin="anonymous"/>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        <Header />
        {children}
        <script
          src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB23Oht8iyYs7SC1UE3Xg5-gxnC6WA_Ib0&loading=async"
          async
        ></script>
      </body>
    </html>
  );
}
